Public class PDFServiceClient {
    
    //Receipt Data
    public class ReceiptData{
        public String donationId;
        public String receiptType;
        public String saleAmt;
        public String soldDate;
        public String pickupDate;
        
        //Added by Offshore 07/13/2015
        //US-102421: Non Standard 8283 letter
        public boolean nonStdVehicle;                                            
    }
    
    
    
    
    
    
    
    
    
    
    
    
    }