public without sharing class ProductCatalogController{


 public Map<String, List<String>> familyGroupMap {get; set;}
List <String>string3=new List<String>();

List <String>string1=new List<String>();
List <String>string2=new List<String>();

public  ProductCatalogController(){

string1.add('A');
string1.add('B');
string1.add('C');




string2.add('D');
string2.add('E');
string2.add('F');





string3.add('G');
string3.add('H');
string3.add('I');


familyGroupMap.put('1st',string1);
familyGroupMap.put('2nd',string2);
familyGroupMap.put('3rd',string3);






}







}